# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demoapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_id', models.CharField(max_length=10)),
                ('ceate_time', models.DateTimeField(auto_now=True)),
                ('demo_content', models.CharField(max_length=50)),
            ],
        ),
    ]
